[package]
name = "ezw"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.31", features = ["derive"] }
clap-verbosity-flag = "3.0.2"
confy = "0.6.1"
exitcode = "1.1.2"
human-panic = "2.0.2"
indicatif = "0.17.11"
log = "0.4.26"
