#!/usr/bin/env bash
#-*- coding: utf-8 -*-

# rustup add platform targets
targets=(
  x86_64-apple-darwin           # macOS Intel
  aarch64-apple-darwin          # macOS Apple Silicon
  x86_64-unknown-linux-gnu      # Linux
  x86_64-pc-windows-gnu         # Windows
)
rustup target add "${targets[@]}"

# homebrew install platform tool_chain
tool_chains=(
  FiloSottile/musl-cross/musl-cross   # Linux
  mingw-w64                           # Windows
)
brew install "${tool_chains[@]}"